service: intl-proxy

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  environment:
    ACCEPTED_USER_NUMBERS: ${file(./keys.${self:provider.stage}.yml):ACCEPTED_USER_NUMBERS}
    TWILIO_ACCOUNT_SID: ${file(./keys.${self:provider.stage}.yml):TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${file(./keys.${self:provider.stage}.yml):TWILIO_AUTH_TOKEN}
    TWILIO_NUMBER: ${file(./keys.${self:provider.stage}.yml):TWILIO_NUMBER}

functions:
  smsReceived:
    handler: handler.smsReceived
    events:
      - http:
          path: smsreceived
          method: post
  twilioCallback:
    handler: handler.twilioCallback
    events:
      - http:
          path: twiliocallback/{number}
          method: post
          request:
            parameters:
              paths:
                number: true

plugins:
  - serverless-mocha-plugin
