service: intl-proxy

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    ACCEPTED_USER_NUMBERS: ${file(./keys.yml):ACCEPTED_USER_NUMBERS}
    TWILIO_ACCOUNT_SID: ${file(./keys.yml):TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${file(./keys.yml):TWILIO_AUTH_TOKEN}
    TWILIO_NUMBER: ${file(./keys.yml):TWILIO_NUMBER}

functions:
  smsReceived:
    handler: handler.smsReceived
    events:
      - http:
          path: smsreceived
          method: post
  twilioCallback:
    handler: handler.twilioCallback
    events:
      - http:
          path: twiliocallback/{number}
          method: post
          request:
            parameters:
              paths:
                number: true
